Sea la matriz:

$$
  A =
  \left[ {\begin{array}{ccc}
    -2 & -4 & 2 \\
    -2 & 1 & 2 \\
    4 & 2 & 5 \\
  \end{array} } \right]
$$

cuyos autovalores son: 3, -5 y 6.


y los vectores 

$$
V_1 = 
\left[ {\begin{array}{c}
    1 \\
    1 \\
    1 \\
  \end{array} } \right]
$$

y 

$$
V_2 = 
\left[ {\begin{array}{c}
    1 \\
    2 \\
    3 \\
  \end{array} } \right] 
$$

# Ejercicio 0

Crear la matriz y los vectores anteriores en numpy.

In [1]:
import numpy as np

A = np.array([[-2, -4, 2],[-2, 1, 2],[4, 2, 5]])
print(A.shape)
V1 = np.array([[1],[1],[1]])
V2 = np.array([[1],[2],[3]])
print(V1.shape)

(3, 3)
(3, 1)


# Ejercicio 1
Dada una matriz en formato numpy array, donde cada fila de la matriz representa un vector matemático, se
requiere computar las normas l0, l1, l2, l-infinity, según la siguientes definiciones:

$||x||_0 =$ cantidad de elementos diferentes a cero en el vector. 

$||x||_p := \big( \sum_{i=1}^{n} |x_i|^p \big)^\frac{1}{p}$ .

$||x||_{\infty} := max_{i} |x_i|$


In [33]:
def vector_norm_l0(matriz):
    Dist_zero = np.abs(matriz) > 0
    return np.sum(Dist_zero, axis=1)


def vector_norm_l1(matriz):
    abs_m = np.abs(matriz)
    return np.sum(abs_m, axis=1)


def vector_norm_l2(matriz):
    return np.sqrt(np.sum(pow(matriz, 2), axis=1))


def vector_norm_inf(matriz):
    return np.max(np.abs(matriz), axis=1)

In [31]:
print("vector_norm_l0(A) \n",vector_norm_l0(A))
print("vector_norm_l1(A) \n",vector_norm_l1(A))
print("vector_norm_l2(A) \n",vector_norm_l2(A))
print("vector_norm_inf(A) \n",vector_norm_inf(A))

vector_norm_l0(A) 
 [3 3 3]
vector_norm_l1(A) 
 [ 8  5 11]
vector_norm_l2(A) 
 [4.89897949 3.         6.70820393]
vector_norm_inf(A) 
 [4 2 5]


# Ejercicio 2
Dada una matriz en formato numpy array, donde cada fila de la matriz representa un vector matemático, se
requiere computar la norma l2 de cada vector.
Una vez obtenida la norma l2 de cada vector, se debe ordenar las normas de mayor a menor.
Finalmente, obtener la matriz original ordenada por fila según la norma l2.
Todas las operaciones debe ser vectorizadas.

**Utilizar el resultado del ejercicio anterior.**

In [64]:
#Matriz_norm_l2=A[np.argsort(vector_norm_l2(A)*-1),:]
Matriz_norm_l2=A[vector_norm_l2(A).argsort()[::-1],:]
print("Matriz_norm_l2 \n",Matriz_norm_l2)

Matriz_norm_l2 
 [[ 4  2  5]
 [-2 -4  2]
 [-2  1  2]]


# Ejercicio 3

Implementar una función que reste la media y divida por el desvío estándar de la matriz A, por columna.

In [79]:
def ResU_DivS(matriz):
    M_matriz = np.mean(A,axis=0)
    D_matriz = np.std(A,axis=0)
    print("media\n",M_matriz)
    print("desviacion\n",D_matriz)
    return (matriz-M_matriz)/D_matriz


In [80]:
print("Funcion del ej3 \n",ResU_DivS(A))

media
 [ 0.         -0.33333333  3.        ]
desviacion
 [2.82842712 2.62466929 1.41421356]
Funcion del ej3 
 [[-0.70710678 -1.3970014  -0.70710678]
 [-0.70710678  0.50800051 -0.70710678]
 [ 1.41421356  0.88900089  1.41421356]]


# Ejercicio 4

Utilizando numpy.linalg, calcular la inversa, el determinante y la traza. Determinar autovalores y autovectores.

In [89]:
def Inversa_matriz(matriz):
    inversa = np.linalg.inv(matriz)
    return inversa

def Determinate_matriz(matriz):
    deter = np.linalg.det(matriz)
    return deter

def Traza_matriz(matriz):
    traza = np.trace(matriz)
    return traza




In [91]:
print(A)
print("Inversa_matriz multiplicada con su original \n",np.dot(A,Inversa_matriz(A)))
print("Determinate_matriz \n",Determinate_matriz(A))
print("Traza \n",Traza_matriz(A))

[[-2 -4  2]
 [-2  1  2]
 [ 4  2  5]]
Inversa_matriz multiplicada con su original 
 [[ 1.00000000e+00  5.55111512e-17  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00  0.00000000e+00]
 [-2.77555756e-17 -8.32667268e-17  1.00000000e+00]]
Determinate_matriz 
 -90.0
Traza 
 4


# Ejercicio 5

Dada una nube de puntos X y centroides C, obtener la distancia entre cada vector X y los centroides
utilizando operaciones vectorizadas y broadcasting en NumPy. Utilizar como referencia los siguientes
valores.

● X = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

● C = [[1, 0, 0], [0, 1, 1]]

In [126]:
def dist_vect(V1,V2):
        #dist = np.linalg.norm(V2-V1)
        diff = V2 - V1
        dist = np.sqrt(np.dot(diff.T, diff))
        return dist


In [128]:
 X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
 C = np.array([[1, 0, 0], [0, 1, 1]])
 print(X)
 print(C)
 print(dist_vect(X,C[0,:]))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 0 0]
 [0 1 1]]
[[ 6.70820393  7.93725393  8.48528137]
 [ 7.93725393  9.64365076 10.39230485]
 [ 8.48528137 10.39230485 11.22497216]]



# Ejercicio 6

Obtener para cada fila en X, el índice de la fila en C con distancia euclídea más pequeña.
Es decir, decir para cada fila en X a qué cluster pertenece en C.
Por ejemplo, si el resultado anterior fue:


[[ 3.60555128 8.36660027 13.45362405]

[ 2.44948974 7.54983444 12.72792206]]


El programa debería devolver [1, 1, 1]


Hint: utilizar np.argmin

In [139]:
Menor_dist_filas = np.argmin(dist_vect(X,C[0,:]), axis=1)
#ind = np.unravel_index(np.argmin(dist_vect(X,C[0,:]), axis=None), dist_vect(X,C[0,:]).shape)
print(Menor_dist_filas)
#print(ind)

[0 0 0]
